### ISSUE TITLE
error after execute command, please help.

### ISSUE THREAD

**Issue by rogerc66** [masterking32/WoWServerWebTerminal#1]
**Got error below:**
`SoapFault exception: [HTTP] Error Fetching http headers in /var/www/WoWServerWebTerminal/ajax.php:34

Stack trace:

#0 [internal function]: SoapClient->__doRequest('
#1 /var/www/WoWServerWebTerminal/ajax.php(34): SoapClient->__call('executeCommand', Array)

#2 {main}`

**my config.php**
`/**
 * @author       Amin Mahmoudi (MasterkinG)
 * @copyright    Copyright (c) 2019 - 2022, MsaterkinG32 Team, Inc. (https://masterking32.com)
 * @link         https://masterking32.com
 * @Github       https://github.com/masterking32/wow-telegram
 * @Description  It's not masterking32 framework !
 */

session_start();

define('Debug_Mode', true); // Change it to true if want enable debug mode.
/**
 * Your soap connection information
 */
$soap_connection_info = array(
    'soap_uri' => 'urn:AC',
    'soap_host' => '127.0.0.1',
    'soap_port' => '7878',
    'soap_user' => '',
    'soap_pass' => '',
);

$admin_username = 'soap';
$admin_password = '123';`

**Comment by jeffalyanak-zadara** [comment]
@rogerc66 Does AC not required a username and password for SOAP? The `soap_user` and `soap_pass` in your config appear to be empty.

**Comment by lesliewang895** [comment]
I have the same trouble.
Some command **can** be executed, but some **can not**.

For example:
I input the command:  account set password user123 aaabbbccc aaabbbccc

The page then display:
SoapFault exception: [HTTP] Error Fetching http headers in c:\www\wowwebcon\ajax.php:35

Stack trace:

#0 [internal function]: SoapClient->__doRequest('
#1 C:\www\wowwebcon\ajax.php(35): SoapClient->__call('executeCommand', Array)

#2 {main}

I use php 7.3.12
